name: run checks
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
          SEQREPO_DATA_PATH: ./tests/data/seqrepo/latest
          AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_DEFAULT_OUTPUT: text
          GENE_NORM_DB_URL: http://localhost:8000
        strategy:
          matrix:
            python-version: ['3.8', '3.9', '3.10', '3.11']
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: {{ matrix.python-version }}

            - name: Install dependencies
              run: python3 -m pip install ".[dev]"

            - run: ruff check fusor/ tests/
